### ISSUE TITLE
Withdraw (Opt-out)

### ISSUE THREAD

**Issue by georgepadayatti** [decentralised-dataexchange/bb-consent-android-privacy-dashboard#5]
It shall be possible to opt out of a previously signed or agreed consent agreement.

- [x] decentralised-dataexchange/bb-consent-android-privacy-dashboard/issues/24
- [x] decentralised-dataexchange/bb-consent-android-privacy-dashboard/issues/25
- [x] decentralised-dataexchange/bb-consent-android-privacy-dashboard/issues/15
